### PR TITLE
Rear MCN Breakout BETA

### PR DESCRIPTION
**Pull request by Victorb101**

### CODE REVIEW

**Comment by Victorb101** [comment]
@aaronbeekay Ready for Version 1.0

**Comment by aaronbeekay** [comment]
@Victorb101 - briefly

* BOM format incorrect
* Gerber .zip file missing drills
* Two copies of .brd and .sch - which is correct?
* Need board .pdfs
* Two approved "Overlap" errors in bottom layer - these are overlaps with a solder nail, but avoidable
* Font on tPlace and bPlace layers should be "Vector", not "Proportional"

**Comment by Victorb101** [comment]
@aaronbeekay Good to go

**Comment by aaronbeekay** [comment]
@Victorb101 Looks good, thanks.

**Pull request merged**
